### ISSUE TITLE
ValueError: Mismatch in the number of predictions (967) and references (0)

### ISSUE THREAD

**Issue by cdqncn** [MiuLab/SpokenCSE#1] opened 2022-07-03 09:58 UTC
Hi，when I run the finetune_on_phonemebert.py , I got this. How should I deal with it?

Thanks!

**Comment by zfrank7777** [comment] 2022-07-06 00:18
Hi,

The issue is currently resolved by downgrade transformers library to 4.15.0. `requirements.txt` is updated.
We will try to update the code to keep up with the latest version, thank you!

**Closed as completed by zfrank7777** 2022-07-06 00:18 UTC
